[project]
name = "new-software"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "258i019i-coder", email = "258i019i@gsuite.kobe-u.ac.jp" }
]
requires-python = ">=3.12"
dependencies = ["pandas",
    "matplotlib"]

[project.scripts]
new-software = "new_software:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
